### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by reedy** [protsack-stephan/mediawiki-api-client#9]
You're publishing code in an open git repo, but not adding a license. So people have no idea if/how they can use the code.

See also: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by protsack-stephan** [comment]
Thanks for noting that. I'll definitely add the license asap.

**Comment by protsack-stephan** [comment]
Thanks again for pointing this out. `Apache-2.0 License` was added closing the issue.
